Adding links for cookies, localstorage,...,web hosting
shrutikapoor08/Learn-Web-Dvelopment-Checklist pull request #17
Opened 2021-04-14 12:05 UTC by cheralathann

I added resource links for cookies, local storage, session storage, server vs client, domain name, DNS, hosting ☺️

2021-04-27 15:52 UTC, sunnykgupta commented
This definitely looks like something that belongs to this list!

2021-06-14 04:37 UTC, shrutikapoor08 approved these changes

2021-06-14 04:38 UTC, shrutikapoor08 requested changes
Requesting one small change

2021-06-14 04:38 UTC, shrutikapoor08 commented on README.md
> +   1. [ ] How does a web browser work? [Link](https://www.youtube.com/watch?v=uE3UPEK26U0&ab_channel=MozillaHacks)
One small change: Could you change [Link] to [Video] for the youtube links? Will be easier for readers to know which ones are videos. Thank you.

2021-06-15 20:20 UTC, shrutikapoor08 approved these changes

2023-01-08 04:19 UTC, closed without merging